### ISSUE TITLE
Cannot create a cubic chunk

### ISSUE THREAD

**Issue by tussiez** [tussiez/sortacraft#4]
build height is small. add support for cubic chunk?

**Comment by tussiez** [comment]
im on it

**Comment by tussiez** [comment]
still cant only works in positive chunks

**Comment by unclescam1234** [comment]
hrrrm that not ggoood

**Comment by tussiez** [comment]
Teah

**Comment by unclescam1234** [comment]
true we need to find a fix

**Comment by tussiez** [comment]
Its a math issue. Here is it explained


If i give sortacraft the player position (12,48,12) i want to get th chunk
at (8,0,8) not (16,0,16) sp the way i am doing righj now is find the
remainedr of the number from 16 and subtract. This worls all fine and dandy
for chunks in positive numbers but negative chunks stop working. Do yoi
have any insight on this math problem?

**Comment by unclescam1234** [comment]
oh

**Comment by tussiez** [comment]
eh
