### ISSUE TITLE
The crouching problem

### ISSUE THREAD

**Issue by unclescam1234** [tussiez/sortacraft#6]
Theres a problem with the crouching when i crouch i just go through the block could you look into that or is that just a thing your still exprimenting on?
thanks

**Comment by tussiez** [comment]
Yeah its just for playtesting & I will remove later when i get the hitbox for the chunk immedatiely

**Comment by unclescam1234** [comment]
ahhhhhhh i see so still not yet ther but cant you make the block under neathe playr soild like when he walks you know why dont you try doing that.

**Comment by tussiez** [comment]
Its basic physics i didnt learn basic physics so its gonna be bad atleast
it works

**Comment by tussiez** [comment]
Fixed!
