### ISSUE TITLE
Trees still spawn in desert

### ISSUE THREAD

**Issue by Gokuman** [tussiez/sortacraft#7]
AAAAAAAAA WHY

**Comment by tussiez** [comment]
They still do? Proof?

**Comment by tussiez** [comment]
Here is code snippet
``
if(type!=3){
``
line 247, chunkworker.js

**Comment by tussiez** [comment]
fixed a long time ago :)

**Comment by Gokuman** [comment]
indeed

**Comment by Gokuman** [comment]
you know its me, harshil, right?
