### ISSUE TITLE
Music and Original Textures

### ISSUE THREAD

**Issue by polygonnedpotato** [tussiez/sortacraft#8]
I can actually provide you with the original music and textures if you want. I got them from my Amazon Fire.

the music contains all of the music from Minecraft including the music disks.
the textures would be full rips from the game as well

**Comment by tussiez** [comment]
Oh those will be kind of illegal

Sorry, but well try to make custom textures

However, this made me think about background music.
It would be very easy to implement

**Comment by polygonnedpotato** [comment]
well, if you don't the original music, there's always using royalty-free music.

**Comment by tussiez** [comment]
Yeah
Thanks for letting me know!

Sorry about message quality, Im replying on phone

**Comment by tussiez** [comment]
Don't need + copyright issues :/
